spring.application.name=bootEco
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:8080/BotEco?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username= postgres
spring.datasource.password= 04032003
spring.datasouce.jpa.show-sql=true
spring.jpa.hibernate.ddl=true
spring.jpa.generate-ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
gemini.api.key=AIzaSyD5YtYav4uO9cJfpym5jccOrJ6pLVkt0Mg
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent