spring.application.name=bootEco
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:8080/BotEco?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username= postgres
spring.datasource.password= 04032003
spring.datasouce.jpa.show-sql=true

spring.jpa.show-sql=true
server.port=8081
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
utalk.api.token=Chat-Boot-2026-04-11-2094-04-30--2400306454C0CB949BE34128D841F41721EB851D2C05821D184299B57F0631AF